apiVersion: v1
kind: Namespace
metadata:
  name: kafka
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-volume
  namespace: kafka
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-volume-2
  namespace: kafka
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-volume-3
  namespace: kafka
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"